config:
  aws:region: ap-southeast-2
  partplanner-backend:containerPort: "8080"
  partplanner-backend:environment: "dev"
  partplanner-backend:project: "template-backend"
  pulumi:template: container-aws-typescript
